# Params for Creating Investors
CONST_PSID_MODELPARAM_INFLATETOYEAR = 'inflateToYear'
CONST_PSID_MODELPARAM_INVESTORFILE_BASE = 'investorInputFile_BaseName_RelativetoBaseDir'
CONST_PSID_MODELPARAM_INDIVIDUAL_CROSSFILE = 'investorCrosswalkfFile_RelativetoBaseDir'
